### ISSUE TITLE
ServerError: AADB2C90205: This application does not have sufficient permissions against this web resource to perform the operation.

### ISSUE THREAD

**Issue by bwhitney2439** [microsoftgraph/msgraph-training-reactspa#36]
Hi All,

I get this error when trying to access Microsoft Graph API via B2C authority. 

ServerError: AADB2C90205: This application does not have sufficient permissions against this web resource to perform the operation.
Correlation ID: e894fe39-b9bf-4441-b3c4-5740ff72fd5e
Timestamp: 2020-04-14 15:39:16Z

This it my config for MSAL library.  i am using the version 1.2.2 of MSAL.  Appears to throw the above error when attempting "acquireTokenSilent" for an access token.

export const config = {
  appId: "appID",
  redirectUri: "http://localhost:3000",
  authority:
    "https://tenantName.b2clogin.com/tenantName.onmicrosoft.com/B2C_1_SUSI",
  scopes: ["https://graph.microsoft.com/User.Read"]
};

I did notice that the builtin b2c-extensions-app that is created when setting up the B2C uses the old Azure Active Directory Graph in it's API permissions.  Not sure if this is related.

Regards,
--
Ben

**Comment by jasonjoh** [comment]
Similar issue in #35, which they fixed by changing the scopes to fully-qualified. I see you've done that, with the only difference being you're using upper-cased scopes. Out of curiosity can you try it with:

```
scopes: ["https://graph.microsoft.com/user.read"]
```

**Comment by bwhitney2439** [comment]
Thanks for quick response @jasonjoh 

Unfortunately changing to lower case still produced the same error.  Interestingly if i create API permissions for the old Azure Active Directory Graph and change the scope to "https://graph.windows.net/User.Read" then i am able to get an access token successfully.

**Comment by Rob97** [comment]
Hello, 

We are being hit with the same error. We have granted all admin permissions as suggested by User gato-negro in issue #35 that was linked above. Is this an issue because it B2C and the patch has not been released yet?

**Comment by jasonjoh** [comment]
Can you provide a bit more context on what you're trying to do? My understanding is that Microsoft Graph is limited in B2C tenants.

- Are you signing into the sample as a B2C user or an admin?
- Are you using the sample as is, or have you modified the requested scopes?

**Comment by jasonjoh** [comment]
I had a good discussion about this with the Microsoft Identity team and got a clearer picture of what is and isn't supposed to work with regards to B2C and Microsoft Graph. The short answer is: this sample doesn't support B2C because apps cannot call Microsoft Graph on behalf of B2C users.

## Longer answer

From the [MSAL.js wiki](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/working-with-b2c.md):

> With B2C:
> 
> - Users can authenticate with their social identities.
> - Users can be authorized to access B2C protected resources (but not AAD protected resources).
> - Users cannot obtain tokens for Microsoft APIs (e.g. MS Graph API) using delegated permissions.
> - Applications can obtain tokens for Microsoft APIs using application permissions (management scenarios).

What this means is you can sign in B2C users with MSAL to get their identity, but you cannot get an access token for Microsoft Graph to act on their behalf. Since that's exactly what this sample attempts to do, it just isn't compatible with B2C users.

B2C supports a [limited set of Graph operations](https://docs.microsoft.com/azure/active-directory-b2c/microsoft-graph-operations), but only by using application permissions via the client credentials flow.
